language : node_js
node_js :
 - stable
install:
 - yarn
script:
 - yarn cover
notifications:
 email:
  on_success: never
  on_failure: always

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"