version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "JavaScript Linter"
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: "JavaScript Test Suite"
          command: yarn jest --runInBand --ci --testResultsProcessor="jest-junit" --coverage --coverageReporters=text-lcov | node_modules/coveralls/bin/coveralls.js
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
