name: Bug Report
description: Report a bug in typescript-json-serializer
title: '[BUG]: '
labels: [bug]
assignees:
    - GillianPerard

body:
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: 'Which version of typescript-json-serializer you use?'
          options:
              - 5.0.0
              - 4.3.0
              - 4.2.0
              - 4.1.1
              - 4.1.0
              - 4.0.1
              - 4.0.0
              - 3.4.5
              - 3.4.4
              - 3.4.3
              - 3.4.2
              - 3.4.1
              - 3.4.0
              - 3.3.0
              - 3.2.2
              - 3.2.1
              - 3.2.0
              - 3.1.0
              - 3.0.0
              - 2.5.3
              - 2.5.2
              - 2.5.1
              - 2.5.0
              - 2.4.1
              - 2.4.0
              - 2.3.4
              - 2.3.3
              - 2.3.2
              - 2.3.1
              - 2.3.0
              - 2.2.1
              - 2.2.0
              - 2.1.0
              - 2.0.0
              - 1.4.6
              - 1.4.5
              - 1.4.4
              - 1.4.3
              - 1.4.2
              - 1.4.1
              - 1.4.0
              - 1.3.0
              - 1.2.5
              - 1.2.4
              - 1.2.3
              - 1.2.2
              - 1.2.1
              - 1.2.0
              - 1.1.0
              - 1.0.9
              - 1.0.8
              - 1.0.6
              - 1.0.5
              - 1.0.4
              - 1.0.3
              - 1.0.2
              - 1.0.1
              - 1.0.0
          multiple: false
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
      validations:
          required: true

    - type: textarea
      id: exception-or-error
      attributes:
          label: Error
          description: Please provide the exception or error you saw
          render: 'Text'

    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: Please provide a minimal code that permits the bug reproduction
      validations:
          required: true

    - type: input
      id: os
      attributes:
          label: On which OS the bug appears?
          placeholder: e.g. Windows 10, macOS 11.4, other
      validations:
          required: true

    - type: input
      id: project-type
      attributes:
          label: What is your project type?
          placeholder: e.g. NodeJs, Angular, React, other
      validations:
          required: true

    - type: input
      id: build-mode
      attributes:
          label: On which build mode the bug appears?
          placeholder: e.g. Development, Production, both

    - type: textarea
      id: other
      attributes:
          label: Anything else?
